config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update]
  resources :favorites, only: [:create, :destroy]
  
  root 'blogs#index'
  resources :blogs do
    collection do
      post :confirm
      get :favorites_index
    end
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  has_one_attached :image

  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog
  has_one_attached :image

  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 30 }, uniqueness: true
  validates :email, presence: true, length: { maximum: 255}, uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: { minimum: 6 }, on: :create

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :check_login_ore_kick_session
  before_action :set_authentication, only: [:edit, :update, :destroy]

  def index
    @blogs = Blog.all.order(created_at: "DESC")
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    else
      if @blog.save
        BlogMailer.blog_mail(@blog).deliver
        redirect_to root_path, notice: "投稿しました。"
      else
        render :new
      end
    end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new unless @blog.valid?
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_url, notice: "記事を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: '記事を削除しました。'
  end

  def favorites_index
    @blog = current_user.favorite_blogs.order(created_at: "DESC")
  end
  
  private
  
  def blog_params
    params.require(:blog).permit(:content, :image)
  end

  def set_authentication
    @blog = Blog.find(params[:id])
    unless current_user == @blog.user
      redirect_to blogs_path, notice: "ユーザーが違います"
    end
  end

  def check_login_ore_kick_session
    unless logged_in?
      redirect_to new_session_url
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to root_path, notice: "お気に入りを登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to root_path, notice: "お気に入りを解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'ログインしました'  #ようこそ＠user＿nameさん
      redirect_to blogs_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_url
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_url, notice: "プロフィールを更新しました。"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end

  def favorite_method
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with( model: @blog, local: true, url: choose_new_or_edit ) do |f| %>

  <% if blog.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% blog.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label '画像' %>
    <%= f.file_field :image, class: 'form-control' %>
    <%= f.label '内容' %>
    <%= f.text_area :content, row: 5, class: 'form-control', id: 'blog_content' %>
  </div>

  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、投稿する。</h3>

<div class="nav.justify-content-end">
  <%= link_to '一覧', blogs_path, class: 'nav-link' %>
</div>

<%= form_with(model: @blog, local: true) do |f| %>
  <div class="form-group">
    <% if @blog.image.attached? %>
      <div class="item"><%= f.label '画像' %></div>
      <div class="item">
        <%= f.hidden_field :image, value: f.object.image.signed_id %>
        <%= image_tag(@blog.image, class: 'image') %>
      </div>
    <% end %>
    <%= f.hidden_field :content %>
    <div class="item"><%= f.label '内容' %></div>
    <div class="item"><%= @blog.content %></div>
  </div>

  <%= f.submit "投稿する", class: 'btn btn-primary' %>
  <%= f.submit "戻る", name: 'back', class: 'btn btn-primary' %>
<% end %>

app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

app/views/blogs/destroy.html.erb
<h1>Blogs#destroy</h1>
<p>Find me in app/views/blogs/destroy.html.erb</p>

app/views/blogs/edit.html.erb
<h3>記事の編集</h3>

<div class="nav.justify-content-end">
  <%= link_to '一覧', blogs_path, class: 'nav-link' %>
</div>

<%= render partial: 'form', locals: { blog: @blog } %>

app/views/blogs/favorites_index.html.erb
<% @blog.each do |blog| %>

  <div class="tweet_box">

    <div class="tweet_head">
      <div class="tweet_head_item">
        <div class="tweet_head_item_user_image">
          <%= image_tag(blog.user.image, class: 'index_image') if blog.user.image.attached? %>
        </div>
        <div class="tweet_head_user_name"><%= blog.user.name %></div>
      </div>

      <div class="tweet_head_show">
        <%= link_to '詳細', blog_path(blog), class: 'show_button' %>
      </div>
    </div>

    <div class="tweet_middle">
      <div class="tweet_middle_item">
        <%= image_tag(blog.image, class: 'image') if blog.image.attached? %>
      </div>
      <div class="tweet_middle_buttons">
        <% if blog.user.name == current_user.name %>
          <%= link_to edit_blog_path(blog), class: 'tweet_icon' do %>
            <%= image_tag "tweet_edit.svg", class: 'tweet_icon_image' %>
          <% end %>
          <%= link_to blog, method: :delete, data: {confirm: "削除してもよろしいですか？"}, class: 'tweet_icon' do %>
            <%= image_tag "tweet_delete.svg", class: 'tweet_icon_image' %>
          <% end %>
        <% else %>
          <% @favorite = @current_user.favorites.find_by(blog_id: blog.id)%>
          <% if @favorite.present?%>
            <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id),
                        method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to 'お気に入りする', favorites_path(blog_id: blog.id),
                        method: :post, class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="tweet_foot">
      <p><%= blog.content %></p>
      <div class="time">
        <time datetime="<%= blog.created_at %>">
          <%= time_ago_in_words(blog.created_at) %>
        </time>
      </div>
    </div>
  </div>
<% end %>

app/views/blogs/index.html.erb
<h3>投稿一覧</h3>

<%= link_to ' 新規投稿', new_blog_path, class: 'create_button' %>

<% @blogs.each do |blog| %>

  <div class="tweet_box">

    <div class="tweet_head">
      <div class="tweet_head_item">
        <div class="tweet_head_item_user_image">
          <%= image_tag(blog.user.image, class: 'index_image') if blog.user.image.attached? %>
        </div>
        <div class="tweet_head_user_name"><%= blog.user.name %></div>
      </div>

      <div class="tweet_head_show">
          <%= link_to '詳細', blog_path(blog), class: 'show_button' %>
      </div>
    </div>

    <div class="tweet_middle">
      <div class="tweet_middle_item">
        <%= image_tag(blog.image, class: 'image') if blog.image.attached? %>
      </div>
      <div class="tweet_middle_buttons">
        <% if blog.user.name == current_user.name %>
          <%= link_to edit_blog_path(blog), class: 'tweet_icon' do %>
            <%= image_tag "tweet_edit.svg", class: 'tweet_icon_image' %>
          <% end %>
          <%= link_to blog, method: :delete, data: {confirm: "削除してもよろしいですか？"}, class: 'tweet_icon' do %>
            <%= image_tag "tweet_delete.svg", class: 'tweet_icon_image' %>
          <% end %>
        <% else %>
          <% @favorite = @current_user.favorites.find_by(blog_id: blog.id)%>
          <% if @favorite.present?%>
            <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id),
                        method: :delete, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to 'お気に入りする', favorites_path(blog_id: blog.id),
                        method: :post, class: 'btn btn-primary' %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="tweet_foot">
      <p><%= blog.content %></p>
      <div class="time">
        <time datetime="<%= blog.created_at %>">
        <%= time_ago_in_words(blog.created_at) %>
       </time>
      </div>
    </div>
  </div>
<% end %>

app/views/blogs/new.html.erb
<h3><%= current_user.name %>さん今何してる？</h3>

<div class="nav.justify-content-end">
  <%= link_to '一覧', blogs_path, class: 'nav-link' %>
</div>

<%= render partial: 'form', locals: { blog: @blog } %>

app/views/blogs/show.html.erb
<h3>投稿の詳細</h3>

<div class="nav.justify-content-end">
  <%= link_to '一覧', blogs_path, class: 'nav-link' %>
</div>

<div class="main_box">
  <div class="main_index">
    <p>ユーザー名</p>
    <p><%=current_user.name %></p>
    <p>作成日時</p>
    <p><%= @blog.created_at.strftime("%Y-%m-%d %H:%M") %></p>
    <p>内容</p>
    <p><%= simple_format(h(@blog.content), {}, sanitize: false, wrapper_tag: "div") %></p>
    <p><%= image_tag(@blog.image, class: 'show_image' ) if @blog.image.attached? %></p>
    <p>更新日時</p>
    <p><%= @blog.updated_at.strftime("%Y-%m-%d %H:%M") %></p>
  </div>
</div>

<% if @blog.user.name == current_user.name %>
  <%= link_to '編集', edit_blog_path, class: 'show_link' %>
  <%= link_to '削除', @blog, method: :delete, data: {confirm: "削除してもよろしいですか？"},
              class: 'show_link' %>
<% else %>

  <%if favorite_method.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id),
                method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id),
                method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/blogs/upadate.html.erb
<h1>Blogs#upadate</h1>
<p>Find me in app/views/blogs/upadate.html.erb</p>

app/views/blogs/update.html.erb
<h1>Blogs#upadate</h1>
<p>Find me in app/views/blogs/upadate.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instaclone</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href='https://fonts.googleapis.com/css?family=Sacramento' rel="styleseet">
  <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
</head>

<header>
  <div class="header_container">
    <div class="title">Instaclone</div>
    <div class="icons">
      <%if logged_in? %>
        <div class="home_icon">
          <%= link_to root_path, class:  'header_icon' do %>
          <%= image_tag "header_home.svg", class: 'header_icon_image' %>
          <% end %>
        </div>
        <div class="favorite_icon">
          <%= link_to favorites_index_blogs_path(current_user.id), class: 'header_icon' do %>
            <%= image_tag "header_favorite.svg", class: 'header_icon_image' %>
          <% end %>
        </div>
        <div class="profile_icon">
          <%= link_to user_path(current_user.id), class: 'header_icon' do %>
            <% if current_user.image.attached? %>
              <%= image_tag(current_user.image, class: 'header_image') %>
            <% else %>
              <%= image_tag "header_profile.svg", class: 'header_icon_image' %>
            <% end %>
          <% end %>
        </div>
        <div class="logout_icon">
          <%= link_to session_path(current_user.id), method: :delete, class: 'header_icon' do %>
            <%= image_tag "header_logout.svg", class: 'header_icon_image' %>
          <% end %>
        </div>
      <% else %>
        <div class="sign_login">
          <%= link_to "新規登録", new_user_path %>
        </div>
        <div class="sign_login">
          <%= link_to "ログイン", new_session_path %>
        </div>
      <% end %>
    </div>
  </div>
</header>

<body>
<div class="body">
  <div class="body_mid">
    <div class="information">
      <% if flash.notice.present? %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
        <% elsif flash.present?%>
        <div class="alert alert-danger">
          <%= flash[:danger] %>
        </div>
        <% else %>
      <% end %>
    </div>
    <%= yield %>
  </div>
</div>
</body>

<footer>
  <div class="footer_container">
    <a class="footer">©︎2020 INSTACLONE FROM FACEBOOK CLONE</a>
  </div>
</footer>

</html>

app/views/users/edit.html.erb
<%= form_with model: @user, local: true do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'ユーザ名' %>
    <%= f.text_field :name, class: 'form-control', id: 'user_name' %>
    <%= f.label '画像' %>
    <%= f.file_field :image, class: 'form-control' %>
    <%= f.label '自己紹介' %>
    <%= f.text_area :introduction, row: 30, class: 'form-control', id: 'user_introduction' %>
  </div>

  <%= f.submit "更新する", class: 'btn btn-primary' %>
<% end %>

app/views/users/new.html.erb
<div class="account_body">
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="account_form">
    <%= form_with(model: @user, local: true) do |f| %>
      <div class="title">Instaclone</div>
      <div class="name_box"><%= f.text_field :name, class: 'account_form_box', :placeholder => "ユーザー名" %></div>
      <div class="email_box"><%= f.email_field :email, class: 'account_form_box', :placeholder => "メールアドレス" %></div>
      <div class="password_box"><%= f.password_field :password, class: 'account_form_box', :placeholder => "パスワード" %></div>
      <div class="password_box2"><%= f.password_field :password_confirmation, class: 'account_form_box', :placeholder => "パスワード確認" %></div>
      <%= f.submit "新規登録", class: 'account_button' %>
    <% end %>
  </div>

  <div class="to_login_or_create_account">
    <p class="comment">アカウントをお持ちですか？
      <%= link_to 'ログインする', new_session_path, class: 'link' %>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile_box">
  <div class="profile_top">
    <div class="profile_image">
      <%= image_tag(@user.image, class: 'show_image') if @user.image.attached? %>
    </div>

    <div class="profile_top_right">
      <div class="profile_name_edit">
        <p class="profile_name"><%= @user.name %></p>
        <p class="button_container"><%= link_to '編集', edit_user_path, class: 'user_edit_button' %></p>
      </div>

      <div class="profile_email_blog_count">
        <p class="profile_email">登録メール　<%= @user.email%></p>
        <p class="profile_blog_count">投稿件数 <%= current_user.blogs.count %>件</p>
      </div>
    </div>
  </div>

  <div class="profile_bottom">
    <% unless @user.introduction.nil? || @user.introduction.blank? %>
      <p>自己紹介</p>
      <p><%= simple_format(h(@user.introduction), {}, sanitize: false, wrapper_tag: "div") %></p>
    <% end %>
  </div>
</div>


<% current_user.blogs.order( created_at: :desc).each do |blog| %>

  <div class="tweet_box">

    <div class="tweet_head">
      <div class="tweet_head_item">
        <div class="tweet_head_item_user_image">
          <%= image_tag(blog.user.image, class: 'index_image') if blog.user.image.attached? %>
        </div>
        <div class="tweet_head_user_name"><%= blog.user.name %></div>
      </div>

      <div class="tweet_head_show">
        <%= link_to '詳細', blog_path(blog), class: 'show_button' %>
      </div>
    </div>

    <div class="tweet_middle">
      <div class="tweet_middle_item">
        <%= image_tag(blog.image, class: 'image') if blog.image.attached? %></div>
      <div class="tweet_middle_buttons">
        <% if blog.user.name == current_user.name %>
          <%= link_to edit_blog_path(blog), class: 'tweet_icon' do %>
            <%= image_tag "tweet_edit.svg", class: 'tweet_icon_image' %>
          <% end %>
          <%= link_to blog, method: :delete, data: {confirm: "削除してもよろしいですか？"}, class: 'tweet_icon' do %>
            <%= image_tag "tweet_delete.svg", class: 'tweet_icon_image' %>
          <% end %>
        <% else %>
        <%= "favorite btn" %>
        <% end %>
      </div>
    </div>

    <div class="tweet_foot">
      <p><%= blog.content %></p>
      <div class="time">
        <time datetime="<%= blog.created_at %>">
          <%= time_ago_in_words(blog.created_at) %>
        </time>
      </div>
    </div>
  </div>
<% end %>